server:
  port: ${PORT:8080}

db:
  username: ${USERNAME:postgres}
  password: ${PASSWORD:toor}
  pool.size: ${POOL_SIZE:20}
  driver-class-name: org.postgresql.Driver
  url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATABASE:postgres}
