server:
  port: 8080

spring:
  jpa:
    properties:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: toor
    pool.size: 20
  liquibase:
    change-log: db.changelog
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
    producer:
      bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      #properties:
        #spring.json.add.type.headers: false
        #max.request.size: 209715200
        #buffer.memory: 209715200

